services:
  jupyter:
    build: 
      context: .
      args:
        REQ_TXT: "requirements.txt"
    image: biobr131/pharmaomicspy:latest
    container_name: jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - .:/usr/src/
    tty: true
    stdin_open: true
